### PR TITLE
Further updates to CommComm

### PR DESCRIPTION
**Pull request by nebrius**
Updates to reflect recent member and observer changes for CommComm meetings

### CODE REVIEW

**Comment by nebrius** [comment]
Merging myself, since this isn't code related. Feel free to tell me not to do this again ;-)

**Comment by rvagg** [comment]
no problems @nebrius, make yourself at home and merge & publish at will. Same goes for other owners: @Trott @jasnell 

If it would make it more comfortable then I'd be happy to move this to a neutral place. I'm not using it myself at all for anything at the moment.

**Comment by nebrius** [comment]
@rvagg I had thought about suggesting moving it to the the nodejs org (and thus under the foundation), since it's specific to running the project. What do you think?

**Comment by rvagg** [comment]
Yep, I'm fine with that, would be good to get contributions to make it more usable across other WGs. Would you mind handling the process of getting this repo up to scratch and getting TSC approval please @nebrius? I'll push it over once approved, I just don't want to be a blocker in the rest of the process.

**Pull request merged**
